# spring:
#   application:
#     name: lab2
#   datasource:
#     url: ${CONTAINER.USERNAME}
#     username: ${CONTAINER.USERNAME}
#     password: ${CONTAINER.PASSWORD}
# flyway:
#   url: ${CONTAINER.USERNAME}
#   user: ${CONTAINER.USERNAME}
#   password: ${CONTAINER.PASSWORD}
#   locations: dbtest/migration
spring:
  datasouce:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:///integration-db